<html>
<head>
	<title>student</title>
</head>
<body>
	学生信息<br>
	学号:${student.id}&nbsp;&nbsp;&nbsp;
	姓名:${student.name}&nbsp;&nbsp;&nbsp;
	年龄:${student.age}&nbsp;&nbsp;&nbsp;
	地址:${student.address}&nbsp;&nbsp;&nbsp;
</body>
</html>